name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"  # a cada 12 horas

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: JoaoNevez
          colors: "#0366d6"

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-p
